### ISSUE TITLE
Honor a TZ env var to set the timezone of the docker image

### ISSUE THREAD

**Issue by mossroy** [atkrad/wait4x#100]
Logs of docker images are currently in UTC timezone.
In most docker images, it's possible to choose a different timezone by passing a "TZ" environment variable.
Could it be also supported in wait4x docker image?

From what I read, it might be as simple as adding the "tzdata" package in the Dockerfile (as your docker image is based on Alpine).
See https://jakeroid.com/blog/how-to-set-timezone-in-your-docker-image/

**Comment by mossroy** [comment]
I'll try to provide a PR for that

**Comment by atkrad** [comment]
> I'll try to provide a PR for that

Thanks @mossroy, It would be nice.
