### ISSUE TITLE
Adjust pipeline to output .exe for Windows instead of file without extension

### ISSUE THREAD

**Issue by sbaeurle** [atkrad/wait4x#105]
If one wants to use Wait4X on Windows or with Windows Containers the current output of the github pipeline cannot be used directly and must be renamed to `wait4x.exe` to become available in both Powershell and CMD.
Is it possible to change the pipeline output to reflect this requirement already?

PS. If needed I can adjust the stuff myself, just wanted to start a discussion about it first.

**Comment by atkrad** [comment]
Hey @sbaeurle,

Thanks for reporting the issue. It would be great if you'd like to send a PR for that.

**Comment by atkrad** [comment]
No, it doesn't. At the "releaser" target in the Dockerfile, we execute the tar command to make an archive file. https://github.com/atkrad/wait4x/blob/main/Dockerfile#L33
But I consider the binary name in the Makefile: https://github.com/atkrad/wait4x/blob/main/Makefile#L88

What is your solution?

**Comment by sbaeurle** [comment]
Okay, got it so far :) I added a separate if check in the Dockerfile that simply renames the binary to `.exe` if TARGETOS is windows.

**Comment by sbaeurle** [comment]
Thanks for the timely help and feedback in the PR :)
