### ISSUE TITLE
Do not reveal passwords in logs

### ISSUE THREAD

**Issue by mossroy** [atkrad/wait4x#177]
It's the case at least with MySQL and PostgreSQL

When wait4x fails to connect (for example because the DNS name does not yet exist under k8s), it outputs something like:

`2023-05-05T23:17:16+02:00 ERR Expectation failed error="failed to establish a connection to the mysql server, caused by: dial tcp: lookup mymariadb on 10.43.0.10:53: no such host" dsn=username:password@tcp(mymariadb:3306)/mydatabase`

or

`2023-05-06T09:57:46+02:00 ERR Expectation failed error="failed to establish a connection to the postgresql server, caused by: dial tcp 10.43.75.241:5432: connect: connection refused" dsn=postgres://username:password@mypostgres:5432/mydatabase?sslmode=disable`

which reveals the password

Ideally, the password would be replaced by stars, or any other means.

**Comment by atkrad** [comment]
It has been released in version [2.14.0](https://github.com/atkrad/wait4x/releases/tag/v2.14.0).
