### ISSUE TITLE
Support POSTing data in http

### ISSUE THREAD

**Issue by Frug** [atkrad/wait4x#25]
It would be nice to be able to specify the http request as a POST request with some body. 

Something like `--with-body '{"foo":"bar"}'` could change the verb to POST and behave like the curl `-d` flag.

**Comment by mortymacs** [comment]
Hi Frug,

That's an excellent idea! Thanks!
We just added it to our plan. It would be great if you'd like to send a PR :)

Cheers,
Mort

**Comment by mortymacs** [comment]
Hi Phil,

That's an excellent idea! Thanks!
We just added it to our plan (`--request-body`). It would be great if you'd like to send a PR :)

Cheers,
Mort
