### ISSUE TITLE
Latest release uses vulnerable stdlib 1.21.6

### ISSUE THREAD

**Issue by poikilotherm** [atkrad/wait4x#329]
Hi there! 

Is there a chance you could release and updated version of this splendid project with a more recent stdlib?

It just doesn't look good on a container image in Scout:
![grafik](https://github.com/user-attachments/assets/eed5d7a7-4d81-4e23-b582-6608eaa5940b)

Using the latest 1.21.13 would at least fix the 9.8 one. Even better would be 1.22.7, as there are more fixes included for some of the "high" scored vuln.

Thank you very much!

**Comment by atkrad** [comment]
Thanks for your report, I'll update it today.

**Comment by atkrad** [comment]
Now you can use the new release: [v2.14.2](https://github.com/atkrad/wait4x/releases/tag/v2.14.2)

**Comment by poikilotherm** [comment]
Thx a ton, I'll test it ASAP!

**Comment by poikilotherm** [comment]
Thx again @atkrad problem solved! Numbers are way down! Way to go!
