### ISSUE TITLE
Wait indefinitely

### ISSUE THREAD

**Issue by mossroy** [atkrad/wait4x#87]
The `--timeout` command-line parameter allows to set a timeout (10s by default).
But I have some cases where I'd like to wait for ever.

Maybe a value of zero could be considered as "for ever"? (It's not the case currently).
Or any other suitable command-line parameter to do that?

**Comment by mossroy** [comment]
I saw that: many thanks!
I'll use it with next released version (but there's no rush)

**Comment by atkrad** [comment]
The feature was released: https://github.com/atkrad/wait4x/releases/tag/v2.7.0

**Comment by mossroy** [comment]
Many thanks! I'm currently using it, and it's perfect for my need
